-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AOC Q3279WG5B 0x00008F0C",
  mode = "2560x1440@59.95",
  position = "1920x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AU Optronics 0x142D",
  mode = "1920x1080@60.05",
  position = "-44x360",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.workspace_rule({ workspace = "1", monitor = "desc:AOC Q3279WG5B 0x00008F0C", default = true, persistent = true })
hl.workspace_rule({ workspace = "2", monitor = "desc:AOC Q3279WG5B 0x00008F0C" })
hl.workspace_rule({ workspace = "3", monitor = "desc:AOC Q3279WG5B 0x00008F0C" })
hl.workspace_rule({ workspace = "4", monitor = "desc:AOC Q3279WG5B 0x00008F0C" })
hl.workspace_rule({ workspace = "5", monitor = "desc:AOC Q3279WG5B 0x00008F0C" })
hl.workspace_rule({ workspace = "6", monitor = "desc:AU Optronics 0x142D", default = true, persistent = true })
hl.workspace_rule({ workspace = "7", monitor = "desc:AU Optronics 0x142D" })
hl.workspace_rule({ workspace = "8", monitor = "desc:AU Optronics 0x142D" })
hl.workspace_rule({ workspace = "9", monitor = "desc:AU Optronics 0x142D" })
